
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mindfull-front-end' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'

  # Pods for mindfull-front-end

plugin 'cocoapods-keys', {
  :project => "mindfull-front-end",
  :target => "mindfull-front-end",
  :keys => [
    "EdamamApplicationKey",
    "EdamamAppId", 
    "SpoonacularApiKey",
    "GoogleID",
  ]
}



end
